// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeT4uWorAWXaP-D9WTPE2HdmTmWWOtOo',
    appId: '1:108991029555:web:c5c52fa31997660aa81e46',
    messagingSenderId: '108991029555',
    projectId: 'tabsnap-2026',
    authDomain: 'tabsnap-2026.firebaseapp.com',
    storageBucket: 'tabsnap-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTSH03FY6A6qnXKRVOfysZiqwOpKLuQM',
    appId: '1:108991029555:android:688a1e7a8d61ae4fa81e46',
    messagingSenderId: '108991029555',
    projectId: 'tabsnap-2026',
    storageBucket: 'tabsnap-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMeEmGJaPrlVclOs6TPtkxn46Bzjd4iY',
    appId: '1:108991029555:ios:06a76b02f026864ca81e46',
    messagingSenderId: '108991029555',
    projectId: 'tabsnap-2026',
    storageBucket: 'tabsnap-2026.firebasestorage.app',
    iosBundleId: 'com.your',
  );
}
